### ISSUE TITLE
remix button

### ISSUE THREAD

**Issue by joshmarinacci** [joshmarinacci/jsconfeu-builder#24]
ppl worked locally then pushed as cut/paste into project (remix button a la Glitch?)

**Comment by tschneidereit** [comment]
I think this is the only change that really requires changes to WebAssembly.studio. Specifically, it requires support for triggering the `fork` function. This would asynchronously trigger the same  postMessage clicking the `fork` button does, which includes the stored project's ID. Note that we could then also use that to store the project itself instead of sending the sources over to the Arch website's server.

Restoring a fork, ready for remixing, just means invoking Wasm Studio with the right GET param, ideally by just loading the code page on the Arch website with the right param, like so: https://experiencethearch.com/code?module=sbkwnndpcnj
